### ISSUE TITLE
You have defined only getMethod.js in PageObjects I require postMethod.js and PUT and Delete

### ISSUE THREAD

**Issue by ilamvazhuthi** [klassijs/klassi-js#58]
You have defined only getMethod.js in PageObjects I require postMethod.js and PUT and Delete. Is it possible to update that ?

**Comment by larryg01** [comment]
Sorry for the late reply, yes i have only written a "GET" method as its a demo, but you can have a look at the actual apiCall function and you will see the code there for POST, PUT AND DELETE methods

**Comment by larryg01** [comment]
I looked into your repo and I am appalled by the fact that you choose to download and rename my repo and also strip it of all its licences files and content. All i ask with the licences i choose to is for you to keep the licence file intact and continue to give me the credit i deserve for making this awesome framework.
Since you have removed the licences file and almost all trace of the fact that its my work, i will no longer help you.
And to make matters worse now that you cannot figure out how to use the function you are asking me for help, impossible impossible
